name: Bynder UI Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run --config validPwd="${{ secrets.UNAME_TOKEN }}"
        uses: cypress-io/github-action@v4
